custom servey page 1 and page 2 model structure implementation
vivektwr/survey_builder pull request #1
Opened 2018-08-14 13:33 UTC by vivektwr

2018-08-16 06:00 UTC, haripcce requested changes

2018-08-16 06:00 UTC, haripcce commented on src/main/java/com/synerzip/survey_builder/models/CustomServey.java
> +	private ObjectId customServeyId;
1. rename from Custom Survey to Survey.
2. customServeyId to id
3. similary rename other fields containing prefix as surevey
4. re design  the survey entity as per the schema design a) e.g questions should be in seperate schema

2018-08-16 06:00 UTC, haripcce commented on src/main/java/com/synerzip/survey_builder/models/ServeyStatus.java
> +public enum ServeyStatus {
spelling mistake ServeyStatus

2018-08-16 06:00 UTC, haripcce commented on src/main/java/com/synerzip/survey_builder/models/ServeyType.java
> +@Document(collection = "servey_type")
spelling mistake for survey

2018-08-16 06:00 UTC, haripcce commented on src/main/java/com/synerzip/survey_builder/models/ServeyType.java
> +	private ObjectId typeId;
No need for separate identifier for id every time. Rename to id everywhere

2018-08-16 06:00 UTC, haripcce commented on pom.xml
>  	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
Add proper description details for the project.

add migration for mongo db and mysql

2018-08-20 05:51 UTC, vivektwr commented
pull request merged

2018-08-20 05:51 UTC, merged